<a href="https://colab.research.google.com/github/PravinTiwari023/Numpy_tutorial_for_Machine_learning/blob/main/01_Numpy_for_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Vector is 1D array

Matrices is 2D array

[Note matrix can have one row and one column]

In [2]:
vector = [1,2,3,4]
matrix = [[1,2,3],[4,5,6],[7,8,9]]

print(vector)
print(matrix)

[1, 2, 3, 4]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [3]:
# Ways of Creating NumPy Array

np_vector = np.array(vector)
np_matrix = np.array(matrix)

print(np_vector)
print(np_matrix)

[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,7,20)

array([0.        , 0.36842105, 0.73684211, 1.10526316, 1.47368421,
       1.84210526, 2.21052632, 2.57894737, 2.94736842, 3.31578947,
       3.68421053, 4.05263158, 4.42105263, 4.78947368, 5.15789474,
       5.52631579, 5.89473684, 6.26315789, 6.63157895, 7.        ])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.16558355, 0.28228465, 0.74888443, 0.41307731, 0.61672271])

In [15]:
np.random.rand(2,5)

array([[0.06742845, 0.75660004, 0.3859053 , 0.55226299, 0.69325722],
       [0.47269912, 0.61484943, 0.9553471 , 0.35024523, 0.34298693]])

In [17]:
#random array

np.random.randn(5)

array([ 0.15630174,  0.54427324,  0.09245262, -1.03443419, -0.37235267])

In [20]:
#random integer from a given range

np.random.randint(12,24)

17

In [21]:
#we can use it for finding random arrays 

random_array = np.random.randint(1,50,10)

print(random_array)

[19 26  2 37  5 17  5 20 43 33]


In [27]:
# simple hand cricket game 

runs = 0
batting = 5
i = 1

while i <= 5:
  bats_man = np.random.randint(0,6)
  baller = np.random.randint(1,6)
  if bats_man == baller :
    print("out")
    i = i + 1
  else :
    runs = runs + bats_man
    print(bats_man,baller)
print("score :",runs)

4 3
out
3 2
0 2
5 4
1 2
2 5
out
1 4
5 3
3 2
3 2
4 3
4 3
1 5
3 1
out
2 1
1 4
0 3
out
out
score : 42


In [28]:
random_array.reshape(2,5)

array([[19, 26,  2, 37,  5],
       [17,  5, 20, 43, 33]])

In [29]:
random_array = np.random.randint(1,50,10)

print(random_array)

[21  7 23 46 30 35 37 27 16 35]


In [30]:
random_array.max()

46

In [31]:
random_array.min()

7

In [32]:
print(random_array)

random_array.argmax()

[21  7 23 46 30 35 37 27 16 35]


3

In [33]:
random_array.argmin()

1

In [34]:
random_array.shape

(10,)