<a href="https://colab.research.google.com/github/PravinTiwari023/Numpy_tutorial_for_Machine_learning/blob/main/02_Numpy_for_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Numpy Indexing and Selection

In [14]:
arr = np.arange(0,11)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [15]:
print(arr[8])
print(arr[1:5])

8
[1 2 3 4]


In [16]:
print(arr[:6])
print(arr[6:])

[0 1 2 3 4 5]
[ 6  7  8  9 10]


In [17]:
arr[:5] = 100

print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [18]:
arr = np.arange(0,11)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
# Slicing

arr_slice = arr[5:]

print(arr_slice)

[ 5  6  7  8  9 10]


In [20]:
arr_slice[:] = 99

print(arr_slice)

[99 99 99 99 99 99]


In [21]:
# It is affacting on original array also

print(arr)

[ 0  1  2  3  4 99 99 99 99 99 99]


In [23]:
# To avoid this, we can use copy funtion

arr_copy = arr.copy()

print(arr_copy)

[ 0  1  2  3  4 99 99 99 99 99 99]


In [24]:
arr_copy[:] = 100

print(arr_copy)

[100 100 100 100 100 100 100 100 100 100 100]


In [26]:
# Now it is not affacting on original array

print(arr)

[ 0  1  2  3  4 99 99 99 99 99 99]


In [29]:
# Lets work with matrices 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# for first element 

# Method 1
print(arr[0][0])

# Method 2
print(arr[0,0])

1
1


In [40]:
#slicing part of np array

arr[:2,1:]

array([[2, 3],
       [5, 6]])

Boolean Indexing

In [47]:
arr = np.arange(0,11)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [48]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [52]:
# boolean array from numpy array

arr_bol = arr > 5

print(arr_bol)

[ True  True  True  True  True]


In [58]:
# Conditional boolean array

arr = arr[arr > 5]

print(arr)

[ 6  7  8  9 10 11 12 13]


In [59]:
arr = np.arange(2,14)

print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [66]:
new_arr = arr[arr%2 == 0]

print(new_arr)

[ 2  4  6  8 10 12]
